# Basic ArgoCD values

server:
  service:
    type: ClusterIP

# Disable High Availability for dev environment to save resources
redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
