apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: mlops-demo-smoke-test
  namespace: argo-workflows
  labels:
    app.kubernetes.io/name: mlops-demo
    workflows.argoproj.io/workflow-template: mlops-demo-template
spec:
  workflowTemplateRef:
    name: mlops-demo-template
  arguments:
    parameters:
      - name: dataset
        value: sample-chest-xray
      - name: model
        value: resnet18-demo
