apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - inference-service.yaml

# Strategic merge patch: override strategy of Deployment created by KServe
# Apply Recreate to never have 2 pods in parallel when deploying
patches:
  - path: deployment-patch.yaml
    target:
      apiVersion: apps/v1
      kind: Deployment
      name: skin-prediction-predictor
      namespace: model-serving
