apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.5.2
      helm:
        releaseName: argocd
        valueFiles:
          - $values/modules/argocd/values.yaml
    - repoURL: https://github.com/xyan-dhgb/mlops-infrastructure.git
      targetRevision: dev
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/metadata/annotations
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      name: argocd-cm
      jsonPointers:
        - /data
