apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  sources:
    - repoURL: https://cloudflare.github.io/helm-charts
      chart: cloudflare-tunnel
      targetRevision: "*"
      helm:
        releaseName: cloudflared
        valueFiles:
          - $values/modules/cloudflare/cloudflare-values.yaml
    - repoURL: https://github.com/xyan-dhgb/mlops-infrastructure.git
      targetRevision: dev
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: false   # Tắt selfHeal — credentials.json inject từ phase2, không sync từ Git
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      name: cloudflared-cloudflare-tunnel
      jsonPointers:
        - /data/credentials.json
