apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  namespace: argocd
  finalizers: []
spec:
  project: platform
  source:
    repoURL: https://github.com/xyan-dhgb/mlops-infrastructure.git
    targetRevision: dev
    path: modules/cloudflare
    helm:
      releaseName: cloudflared
      valueFiles:
        - cloudflare-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      name: cloudflared-cloudflare-tunnel
      jsonPointers:
        - /data/credentials.json
