apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: mlflow
      targetRevision: 0.7.19
      helm:
        releaseName: mlflow-server
        valueFiles:
          - $values/modules/mlflow/values.yaml
    - repoURL: https://github.com/xyan-dhgb/mlops-infrastructure.git
      targetRevision: dev
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: false   # Tắt selfHeal — configmap/secret chứa runtime values inject từ phase2
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Secret
      name: mlflow-server-env-secret
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      name: mlflow-server-env-configmap
      jsonPointers:
        - /data
