apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers: []
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.6.2
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/modules/monitoring/prometheus/prometheus-values.yaml
    - repoURL: https://github.com/xyan-dhgb/mlops-infrastructure.git
      targetRevision: dev
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
    - group: monitoring.coreos.com
      kind: PrometheusRule
      jsonPointers:
        - /spec/groups
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
