apiVersion: v1
kind: Service
metadata:
  name: cicd-metrics-exporter
  namespace: prometheus
  labels:
    app.kubernetes.io/name: cicd-metrics-exporter
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  selector:
    app.kubernetes.io/name: cicd-metrics-exporter
  ports:
    - name: http
      port: 8080
      targetPort: http
