apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cicd-metrics-exporter
  namespace: prometheus
  labels:
    release: prometheus
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: cicd-metrics-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
