# This is for Prometheus K8s namespace

# Disable Grafana because it will be installed in a separate namespace
grafana:
  enabled: false

# Prometheus configuration
# The Prometheus and Alertmanager configuration utilizes the Node's ephemeral storage (Node's disk/RAM) instead of requiring AWS to allocate expensive EBS (Persistent Volume) hard drives.
prometheus:
  prometheusSpec:
    # Ephemeral storage - no PVC/EBS
    storageSpec: {}
    # Only store metrics data for 1 day
    retention: 1d

# Alertmanager configuration
alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: __ALERT_SMTP_USERNAME__
      smtp_auth_username: __ALERT_SMTP_USERNAME__
      smtp_auth_identity: __ALERT_SMTP_USERNAME__
      smtp_auth_password: __ALERT_SMTP_PASSWORD__
      smtp_require_tls: true
    inhibit_rules:
      - source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
        equal:
          - namespace
          - alertname
      - source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
        equal:
          - namespace
          - alertname
      - source_matchers:
          - alertname = InfoInhibitor
        target_matchers:
          - severity = info
        equal:
          - namespace
      - target_matchers:
          - alertname = InfoInhibitor
    route:
      group_by:
        - alertname
        - namespace
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: eks-email
      routes:
        - receiver: "null"
          matchers:
            - alertname = "Watchdog"
    receivers:
      - name: "null"
      - name: eks-email
        email_configs:
          - to: kltn-grafana-alertmanager@googlegroups.com
            send_resolved: true
  alertmanagerSpec:
    # Ephemeral storage - no PVC/EBS
    storage:
      emptyDir: {}
